# Generated by Django 2.0.3 on 2019-06-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="dinner_platters", name="large_price", field=models.FloatField()
        ),
        migrations.AlterField(
            model_name="dinner_platters", name="small_price", field=models.FloatField()
        ),
        migrations.AlterField(
            model_name="pasta", name="price", field=models.FloatField()
        ),
        migrations.AlterField(
            model_name="pizza", name="large_price", field=models.FloatField()
        ),
        migrations.AlterField(
            model_name="pizza", name="small_price", field=models.FloatField()
        ),
        migrations.AlterField(
            model_name="salads", name="price", field=models.FloatField()
        ),
        migrations.AlterField(
            model_name="subs", name="large_price", field=models.FloatField()
        ),
        migrations.AlterField(
            model_name="subs", name="small_price", field=models.FloatField()
        ),
    ]
