# Generated by Django 2.0.3 on 2019-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0003_auto_20190618_1510")]

    operations = [
        migrations.AlterField(
            model_name="pizza", name="style", field=models.CharField(max_length=64)
        )
    ]
