# Generated by Django 2.0.3 on 2019-06-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0006_order_order_total")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        )
    ]
