# Generated by Django 2.0.3 on 2019-06-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0008_auto_20190621_1239")]

    operations = [
        migrations.RemoveField(model_name="pizza", name="style"),
        migrations.AlterField(
            model_name="pizza", name="name", field=models.CharField(max_length=255)
        ),
    ]
