# Generated by Django 2.0.3 on 2019-06-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0010_order_date")]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="extras",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        )
    ]
