# Generated by Django 2.0.3 on 2019-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0011_cart_extras")]

    operations = [
        migrations.CreateModel(
            name="Extras",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("small_price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("large_price", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        )
    ]
