# Generated by Django 2.0.3 on 2019-06-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orders", "0012_extras")]

    operations = [migrations.RenameModel(old_name="Extras", new_name="Extra")]
