# Generated by Django 2.0.3 on 2019-06-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orders", "0013_auto_20190623_1553")]

    operations = [
        migrations.RenameField(
            model_name="extra", old_name="large_price", new_name="price"
        ),
        migrations.RemoveField(model_name="extra", name="small_price"),
    ]
